### ISSUE TITLE
Hierachies not being read correctly

### ISSUE THREAD

**Issue by dsdd** [Osiris-Team/Dream-Yaml#1]
Suppose I have the following yaml:

```
something: true
alot_of_things:
  athing: "something is not right"
  anotherthing: "nah its right"
```

When I save it, it becomes this:

```
something: true
something:
  athing: "something is not right"
  anotherthing: "nah its right"
alot_of_things:
  athing:
  anotherthing:
```

Any idea on why this is happening?

**Comment by Osiris-Team** [comment]
@dsdd Can you also provide your java code?

**Comment by Osiris-Team** [comment]
@dsdd I tried it by myself:
Code:
```java
DreamYaml yaml = new DreamYaml(System.getProperty("user.dir") + "/issue-1.yml");
        yaml.load();

        yaml.add("something").setDefValue("true");
        yaml.add("alot_of_things", "athing").setDefValue("something is not right");
        yaml.add("alot_of_things", "anotherthing").setDefValue("nah its right");

        yaml.save();
```
Output YAML:
```yaml
something: true
alot_of_things: 
  athing: something is not right
  anotherthing: nah its right
```

**Comment by dsdd** [comment]
> @dsdd I tried it by myself and couldn't find any issue.
> Code:
> 
> ```java
> DreamYaml yaml = new DreamYaml(System.getProperty("user.dir") + "/issue-1.yml");
>         yaml.load();
> 
>         yaml.add("something").setDefValue("true");
>         yaml.add("alot_of_things", "athing").setDefValue("something is not right");
>         yaml.add("alot_of_things", "anotherthing").setDefValue("nah its right");
> 
>         yaml.save();
> ```
> 
> Output YAML:
> 
> ```yaml
> something: true
> alot_of_things: 
>   athing: something is not right
>   anotherthing: nah its right
> ```

Writing to the file is not a problem, it's the reading. If I paste my yaml file and try to read it it will print the result

**Comment by dsdd** [comment]
> @dsdd Can you also provide your java code?

DreamYaml yaml = new DreamYaml(file).load();
DYModule something = yaml.getLoadedModuleByKeys("something"); // Would use add() but it prints a DuplicateKeyException, maybe you can automatically use getLoadedModuleByKeys if there's a duplicate so no one has to check for key existence?
DYModule anotherthing = yaml.getLoadedModuleByKeys("alot_of_things", "anotherthing");
something.setValue(false);
yaml.save();

**Comment by Osiris-Team** [comment]
@dsdd There was indeed a small bug in the getLoadedModuleByKeys() method. It was looking for the 'added modules' list instead of the 'loaded modules' list.
It would be great if you update to the latest version of Dream-Yaml (v2.3) and test if it worked.

**Comment by Osiris-Team** [comment]
@dsdd updated to 2.4

**Comment by dsdd** [comment]
Still doesn't work, I've tried this without hierarchies too and doing yaml.load() and yaml.save() just completely wipes out the yaml file, does saving only save added modules?

**Comment by Osiris-Team** [comment]
@dsdd updated to 2.5. I'm pretty sure now it works. You also should use the add() method if you want to change any values.
Code:
```java
DreamYaml yaml = new DreamYaml(System.getProperty("user.dir") + "/src/test/issue-1.yml")
                .load();

        DYModule something = yaml.add("something")
                .setValue("false");
        DYModule anotherthing = yaml.add("alot_of_things", "anotherthing")
                .setValue("Wow it actually works!");
        yaml.save();
```
Output YAML:
```yaml
something: false
alot_of_things: 
  athing: "something is not right"
  anotherthing: Wow it actually works!

```
