### ISSUE TITLE
: in list causes line break?

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/Dream-Yaml#15]
test:
```yaml
list:
  - hello: there
```
output:
```yaml
list:
  - hello: there
    -
    -
...
``

**Comment by Rubenicos** [comment]
Load it as a map object:
```yaml
list:
  - Hello # (String object)
  
  - key: value # (Single map object)
  
  # (Map object with maps has values)
  - key:
      subkey: value # (Single map object)
      otherkey: value # (Single map object)
    key2:
      subkey: value # (Single map object)
      
  - key: # (Single map object with list has value)
      - value1 # (String object)
      - key: value # (Single map object)
      - value2 # (String object)
      
  - Hi # (String object)
```
