### ISSUE TITLE
Add DB like behavior 

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/Dream-Yaml#4]
A single YAML file could be divided into tables.
Example:
```yaml
tables:
  - table1Name:
      - column1:
         - "This value is in column1" # First row
         - "Another value"
         - 
      - column2:
         -  "This value is in colum2"   
         -      # This means there is no value
         -  "" # This means the value is empty

  # A tastier example
  - favorite-food:
     food, likes:
       - 1: "Bread" "1240" 
       - 2: "Milk" "889"  
```
