### ISSUE TITLE
Add line spacing

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/Dream-Yaml#9]
Methods:
```java
module.getTopLineSpacing() // Returns int representing the amount of empty lines to the next upper module
module.setTopLineSpacing() 

module.getBottomLineSpacing() // Returns int representing the amount of empty lines to the next lower module
module.setBottomLineSpacing()
```
Example usage:
```yaml
m1: val # has 0 top line spacings and 0 bottom line spacings
m2: val # has 0 top line spacings and 2 bottom line spacings 


m3: val # has 2 top line spacings and 0 bottom line spacings 
```
Lets imagine we set the 'm2' modules bottom line spacings to 4?
Then what happens to the "m3" module?
Edit we could remove `setBottomLineSpacing()` and only use `setTopLineSpacing()` instead, to prevent that inconsitency between modules.

What about comments?
Since the line spacing is between modules (a comment is part of a module) the comment wouldn't have line spacings to its key.
